name: CI workflow

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install
        working-directory: ./back
        run: npm ci
      - name: Tests
        working-directory: ./back
        run: npm test